package main

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"
)

// Message represents a single chat message formatted in the OpenAI Chat Completions API schema.
type Message struct {
	Role       string     `json:"role"`                 // Message role: "system", "user", "assistant", or "tool"
	Content    string     `json:"content,omitempty"`      // Text content of the message
	ToolCalls  []ToolCall `json:"tool_calls,omitempty"`   // Array of tool calls emitted by the assistant
	ToolCallID string     `json:"tool_call_id,omitempty"` // ID of the tool call this message responds to (for role="tool")
}

// ToolCall represents a function call emitted by the model.
type ToolCall struct {
	Index    int          `json:"index"`            // Index of the tool call in incremental streaming chunks
	ID       string       `json:"id,omitempty"`       // Unique call ID generated by the model
	Type     string       `json:"type,omitempty"`     // Call type (typically "function")
	Function FunctionCall `json:"function"`         // Executable function name and JSON arguments
}

// FunctionCall describes a specific tool name and argument JSON string payload.
type FunctionCall struct {
	Name      string `json:"name,omitempty"`      // Function/tool identifier
	Arguments string `json:"arguments,omitempty"` // Raw JSON argument payload
}

// ToolSpec defines a callable tool in the OpenAI function-calling schema.
type ToolSpec struct {
	Type     string       `json:"type"`     // Spec type (typically "function")
	Function ToolFunction `json:"function"` // Function definition
}

// ToolFunction contains the name, description, and JSON schema parameters for a tool.
type ToolFunction struct {
	Name        string          `json:"name"`        // Function name
	Description string          `json:"description"` // Function purpose description for LLM reasoning
	Parameters  json.RawMessage `json:"parameters"`  // JSON schema specifying parameter types and required fields
}

type chatRequest struct {
	Model    string     `json:"model"`
	Messages []Message  `json:"messages"`
	Tools    []ToolSpec `json:"tools,omitempty"`
	Stream   bool       `json:"stream"`
}

type streamChunk struct {
	Choices []struct {
		Delta struct {
			Content   string     `json:"content"`
			ToolCalls []ToolCall `json:"tool_calls"`
		} `json:"delta"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Error *struct {
		Code    string `json:"code"`
		Message string `json:"message"`
		Type    string `json:"type"`
	} `json:"error"`
}

// StreamEvent represents a single token delta or completion event emitted during streaming.
type StreamEvent struct {
	Text         string     // Streamed text token fragment
	Done         bool       // True when the turn completion ends
	ToolCalls    []ToolCall // Reassembled complete tool calls (present on Done=true)
	FinishReason string     // Upstream completion finish reason
	Err          error      // Non-nil if a stream or upstream error occurred
}

// streamChat invokes the OpenAI-compatible /chat/completions endpoint with stream=true and
// yields StreamEvents on the returned channel as content deltas and tool-call fragments arrive.
func streamChat(ctx context.Context, cfg *Config, messages []Message, tools []ToolSpec) <-chan StreamEvent {
	out := make(chan StreamEvent, 8)

	go func() {
		defer close(out)

		reqCtx, cancel := context.WithTimeout(ctx, 150*time.Second)
		defer cancel()
		stallTimer := time.AfterFunc(30*time.Second, cancel)
		defer stallTimer.Stop()

		reqBody := chatRequest{
			Model:    cleanModelName(cfg.Model),
			Messages: messages,
			Tools:    tools,
			Stream:   true,
		}
		buf, err := json.Marshal(reqBody)
		if err != nil {
			out <- StreamEvent{Err: fmt.Errorf("encode request: %w", err)}
			return
		}

		url := strings.TrimRight(cfg.BaseURL, "/") + "/chat/completions"
		req, err := http.NewRequestWithContext(reqCtx, http.MethodPost, url, bytes.NewReader(buf))
		if err != nil {
			out <- StreamEvent{Err: fmt.Errorf("build request: %w", err)}
			return
		}
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("Accept", "text/event-stream")
		if cfg.APIKey != "" {
			req.Header.Set("Authorization", "Bearer "+cfg.APIKey)
		}

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			out <- StreamEvent{Err: fmt.Errorf("request failed: %w", err)}
			return
		}
		defer resp.Body.Close()

		if resp.StatusCode != http.StatusOK {
			body := make([]byte, 4096)
			n, _ := resp.Body.Read(body)
			out <- StreamEvent{Err: fmt.Errorf("upstream returned %s: %s", resp.Status, string(body[:n]))}
			return
		}

		toolAcc := map[int]*ToolCall{}
		var order []int
		finishReason := ""

		scanner := bufio.NewScanner(resp.Body)
		scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
		debug := os.Getenv("OPENCODE_TINY_DEBUG") != ""
		for scanner.Scan() {
			line := scanner.Text()
			if debug {
				fmt.Fprintf(os.Stderr, "[sse] %s\n", line)
			}
			if !strings.HasPrefix(line, "data: ") {
				continue
			}
			stallTimer.Stop()
			payload := strings.TrimPrefix(line, "data: ")
			if payload == "[DONE]" {
				break
			}

			var chunk streamChunk
			if err := json.Unmarshal([]byte(payload), &chunk); err != nil {
				continue
			}
			if chunk.Error != nil {
				out <- StreamEvent{Err: fmt.Errorf("upstream error [%s/%s]: %s", chunk.Error.Type, chunk.Error.Code, chunk.Error.Message)}
				return
			}
			if len(chunk.Choices) == 0 {
				continue
			}
			choice := chunk.Choices[0]

			if choice.Delta.Content != "" {
				out <- StreamEvent{Text: choice.Delta.Content}
			}

			for _, tc := range choice.Delta.ToolCalls {
				existing, ok := toolAcc[tc.Index]
				if !ok {
					existing = &ToolCall{Index: tc.Index, Type: "function"}
					toolAcc[tc.Index] = existing
					order = append(order, tc.Index)
				}
				if tc.ID != "" {
					existing.ID = tc.ID
				}
				if tc.Function.Name != "" {
					existing.Function.Name += tc.Function.Name
				}
				if tc.Function.Arguments != "" {
					existing.Function.Arguments += tc.Function.Arguments
				}
			}

			if choice.FinishReason != "" {
				finishReason = choice.FinishReason
			}
		}
		if err := scanner.Err(); err != nil {
			out <- StreamEvent{Err: fmt.Errorf("stream read error: %w", err)}
			return
		}

		var finalCalls []ToolCall
		for _, idx := range order {
			finalCalls = append(finalCalls, *toolAcc[idx])
		}

		out <- StreamEvent{Done: true, ToolCalls: finalCalls, FinishReason: finishReason}
	}()

	return out
}

// isTransientUpstreamError identifies recoverable network/gateway errors suitable for transparent retry.
func isTransientUpstreamError(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	for _, marker := range []string{
		"502", "503", "upstream_error",
		"deadline exceeded", "context canceled",
		"EOF",
		"connection reset",
	} {
		if strings.Contains(msg, marker) {
			return true
		}
	}
	return false
}

// streamChatWithRetry wraps streamChat with exponential backoff retries for transient initial connection failures.
func streamChatWithRetry(ctx context.Context, cfg *Config, messages []Message, tools []ToolSpec) <-chan StreamEvent {
	out := make(chan StreamEvent, 8)

	go func() {
		defer close(out)

		const maxAttempts = 3
		backoff := time.Second

		for attempt := 1; attempt <= maxAttempts; attempt++ {
			ch := streamChat(ctx, cfg, messages, tools)
			first, ok := <-ch
			if !ok {
				return
			}

			if first.Err != nil && isTransientUpstreamError(first.Err) && attempt < maxAttempts {
				select {
				case <-ctx.Done():
					out <- StreamEvent{Err: ctx.Err()}
					return
				case <-time.After(backoff):
				}
				backoff *= 2
				continue
			}

			out <- first
			for ev := range ch {
				out <- ev
			}
			return
		}
	}()

	return out
}

// cleanModelName strips provider namespace prefixes (e.g. "openmind/zen-deepseek-v4-flash-free" -> "zen-deepseek-v4-flash-free").
func cleanModelName(model string) string {
	if idx := strings.LastIndex(model, "/"); idx != -1 {
		return model[idx+1:]
	}
	return model
}
