package main

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"
)

// Message represents a single chat message formatted in the OpenAI Chat Completions API schema.
type Message struct {
	Role       string     `json:"role"`                   // Message role: "system", "user", "assistant", or "tool"
	Content    any        `json:"content"`                // Text content string OR multimodal []any (must not be omitted)
	ToolCalls  []ToolCall `json:"tool_calls,omitempty"`   // Array of tool calls emitted by the assistant
	ToolCallID string     `json:"tool_call_id,omitempty"` // ID of the tool call this message responds to (for role="tool")
}

// ToolCall represents a function call emitted by the model.
type ToolCall struct {
	Index    int          `json:"index"`          // Index of the tool call in incremental streaming chunks
	ID       string       `json:"id,omitempty"`   // Unique call ID generated by the model
	Type     string       `json:"type,omitempty"` // Call type (typically "function")
	Function FunctionCall `json:"function"`       // Executable function name and JSON arguments
}

// FunctionCall describes a specific tool name and argument JSON string payload.
type FunctionCall struct {
	Name      string `json:"name,omitempty"`      // Function/tool identifier
	Arguments string `json:"arguments,omitempty"` // Raw JSON argument payload
}

// ToolSpec defines a callable tool in the OpenAI function-calling schema.
type ToolSpec struct {
	Type     string       `json:"type"`     // Spec type (typically "function")
	Function ToolFunction `json:"function"` // Function definition
}

// ToolFunction contains the name, description, and JSON schema parameters for a tool.
type ToolFunction struct {
	Name        string          `json:"name"`        // Function name
	Description string          `json:"description"` // Function purpose description for LLM reasoning
	Parameters  json.RawMessage `json:"parameters"`  // JSON schema specifying parameter types and required fields
}

type chatRequest struct {
	Model    string     `json:"model"`
	Messages []Message  `json:"messages"`
	Tools    []ToolSpec `json:"tools,omitempty"`
	Stream   bool       `json:"stream"`
}

type streamChunk struct {
	Choices []struct {
		Delta struct {
			Content   string     `json:"content"`
			ToolCalls []ToolCall `json:"tool_calls"`
		} `json:"delta"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Error *struct {
		Code    string `json:"code"`
		Message string `json:"message"`
		Type    string `json:"type"`
	} `json:"error"`
}

// StreamEvent represents a single token delta or completion event emitted during streaming.
type StreamEvent struct {
	Text         string     // Streamed text token fragment
	Done         bool       // True when the turn completion ends
	ToolCalls    []ToolCall // Reassembled complete tool calls (present on Done=true)
	FinishReason string     // Upstream completion finish reason
	Err          error      // Non-nil if a stream or upstream error occurred
}

var knownToolNames = []string{
	"bash", "websearch", "webfetch", "read_file", "write_file", "edit_file",
	"superuser_access", "gpio_control", "host_shell",
}

func sanitizeToolName(name string) string {
	name = strings.TrimSpace(name)
	for _, known := range knownToolNames {
		if name == known {
			return name
		}
	}
	// Check if known tool name is a prefix (e.g. websearchwebsearchwebfetch -> websearch)
	for _, known := range knownToolNames {
		if strings.HasPrefix(name, known) {
			return known
		}
	}
	// Check if known tool name is contained
	for _, known := range knownToolNames {
		if strings.Contains(name, known) {
			return known
		}
	}
	return "bash"
}

func sanitizeToolArguments(args string) string {
	args = strings.TrimSpace(args)
	if args == "" {
		return "{}"
	}
	var test any
	if err := json.Unmarshal([]byte(args), &test); err == nil {
		return args
	}
	// If arguments contain multiple concatenated JSON objects (e.g. {"a":1}{"b":2})
	dec := json.NewDecoder(strings.NewReader(args))
	var first json.RawMessage
	if err := dec.Decode(&first); err == nil && len(first) > 0 {
		return string(first)
	}
	return "{}"
}

// sanitizeMessages filters and fixes message history to ensure strict OpenAI API schema conformance:
// 1. Removes empty assistant messages (no tool_calls and empty content).
// 2. Fixes corrupted tool names (e.g. websearchwebsearchwebfetch) and concatenated JSON arguments.
// 3. Fixes orphaned assistant tool_calls that are not followed by matching tool response messages (e.g. from interrupted turns).
// 4. Removes orphaned tool messages that have no preceding assistant with tool_calls.
// 5. Ensures all user and system messages have non-nil content.
func sanitizeMessages(msgs []Message) []Message {
	if len(msgs) == 0 {
		return msgs
	}

	var step1 []Message
	for _, m := range msgs {
		switch m.Role {
		case "assistant":
			if len(m.ToolCalls) == 0 {
				if str, ok := m.Content.(string); ok && strings.TrimSpace(str) == "" {
					continue
				}
				if m.Content == nil {
					continue
				}
			} else {
				// Sanitize tool call names and arguments
				for j := range m.ToolCalls {
					m.ToolCalls[j].Function.Name = sanitizeToolName(m.ToolCalls[j].Function.Name)
					m.ToolCalls[j].Function.Arguments = sanitizeToolArguments(m.ToolCalls[j].Function.Arguments)
					if m.ToolCalls[j].ID == "" {
						m.ToolCalls[j].ID = fmt.Sprintf("call_%d", j)
					}
					m.ToolCalls[j].Type = "function"
				}
			}
			step1 = append(step1, m)
		case "tool":
			if str, ok := m.Content.(string); ok && str == "" {
				m.Content = "(no output)"
			}
			if m.Content == nil {
				m.Content = "(no output)"
			}
			step1 = append(step1, m)
		case "user", "system":
			if m.Content == nil {
				m.Content = ""
			}
			step1 = append(step1, m)
		default:
			step1 = append(step1, m)
		}
	}

	// Step 2: Validate and pair tool calls with tool responses
	var clean []Message
	for i := 0; i < len(step1); i++ {
		m := step1[i]
		if m.Role == "assistant" && len(m.ToolCalls) > 0 {
			// Count how many matching tool messages follow immediately
			neededIDs := make(map[string]bool)
			for _, tc := range m.ToolCalls {
				if tc.ID != "" {
					neededIDs[tc.ID] = true
				}
			}

			// Look ahead for matching tool messages
			foundAll := true
			lookahead := i + 1
			for tcID := range neededIDs {
				found := false
				for j := lookahead; j < len(step1); j++ {
					if step1[j].Role != "tool" {
						break
					}
					if step1[j].ToolCallID == tcID {
						found = true
						break
					}
				}
				if !found {
					foundAll = false
					break
				}
			}

			if !foundAll {
				// Dangling tool call: strip tool calls and preserve content
				m.ToolCalls = nil
				if str, ok := m.Content.(string); !ok || strings.TrimSpace(str) == "" {
					m.Content = "(interrupted)"
				}
			}
			clean = append(clean, m)
		} else if m.Role == "tool" {
			// Only include tool message if preceding message in clean was assistant with tool_calls
			if len(clean) > 0 && clean[len(clean)-1].Role == "assistant" && len(clean[len(clean)-1].ToolCalls) > 0 {
				clean = append(clean, m)
			} else {
				// Convert orphaned tool message into user observation note to preserve context without schema error
				clean = append(clean, Message{
					Role:    "user",
					Content: fmt.Sprintf("[Tool observation: %v]", m.Content),
				})
			}
		} else {
			clean = append(clean, m)
		}
	}

	return clean
}

// streamChat invokes the OpenAI-compatible /chat/completions endpoint with stream=true and
// yields StreamEvents on the returned channel as content deltas and tool-call fragments arrive.
func streamChat(ctx context.Context, cfg *Config, messages []Message, tools []ToolSpec) <-chan StreamEvent {
	out := make(chan StreamEvent, 8)

	go func() {
		defer close(out)

		reqCtx, cancel := context.WithTimeout(ctx, 150*time.Second)
		defer cancel()
		stallTimer := time.AfterFunc(30*time.Second, cancel)
		defer stallTimer.Stop()

		cleanedMsgs := sanitizeMessages(pruneMessagesForContext(messages))
		reqBody := chatRequest{
			Model:    cleanModelName(cfg.Model),
			Messages: cleanedMsgs,
			Tools:    tools,
			Stream:   true,
		}
		buf, err := json.Marshal(reqBody)
		if err != nil {
			out <- StreamEvent{Err: fmt.Errorf("encode request: %w", err)}
			return
		}

		url := strings.TrimRight(cfg.BaseURL, "/") + "/chat/completions"
		req, err := http.NewRequestWithContext(reqCtx, http.MethodPost, url, bytes.NewReader(buf))
		if err != nil {
			out <- StreamEvent{Err: fmt.Errorf("build request: %w", err)}
			return
		}
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("Accept", "text/event-stream")
		if cfg.APIKey != "" {
			req.Header.Set("Authorization", "Bearer "+cfg.APIKey)
		}

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			out <- StreamEvent{Err: fmt.Errorf("request failed: %w", err)}
			return
		}
		defer resp.Body.Close()

		if resp.StatusCode != http.StatusOK {
			body := make([]byte, 4096)
			n, _ := resp.Body.Read(body)
			out <- StreamEvent{Err: fmt.Errorf("upstream returned %s: %s", resp.Status, string(body[:n]))}
			return
		}

		var accumulated []*ToolCall
		finishReason := ""

		scanner := bufio.NewScanner(resp.Body)
		scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
		debug := os.Getenv("OPENCODE_TINY_DEBUG") != ""
		for scanner.Scan() {
			line := scanner.Text()
			if debug {
				fmt.Fprintf(os.Stderr, "[sse] %s\n", line)
			}
			if !strings.HasPrefix(line, "data: ") {
				continue
			}
			stallTimer.Stop()
			payload := strings.TrimPrefix(line, "data: ")
			if payload == "[DONE]" {
				break
			}

			var chunk streamChunk
			if err := json.Unmarshal([]byte(payload), &chunk); err != nil {
				continue
			}
			if chunk.Error != nil {
				out <- StreamEvent{Err: fmt.Errorf("upstream error [%s/%s]: %s", chunk.Error.Type, chunk.Error.Code, chunk.Error.Message)}
				return
			}
			if len(chunk.Choices) == 0 {
				continue
			}
			choice := chunk.Choices[0]

			if choice.Delta.Content != "" {
				out <- StreamEvent{Text: choice.Delta.Content}
			}

			for _, tc := range choice.Delta.ToolCalls {
				var target *ToolCall
				if tc.ID != "" {
					// Check if tool call with this ID already exists
					for _, existing := range accumulated {
						if existing.ID == tc.ID {
							target = existing
							break
						}
					}
					if target == nil {
						// Create a new tool call
						target = &ToolCall{
							Index: len(accumulated),
							ID:    tc.ID,
							Type:  "function",
						}
						accumulated = append(accumulated, target)
					}
				} else if tc.Index > 0 && tc.Index < len(accumulated) {
					target = accumulated[tc.Index]
				} else if len(accumulated) > 0 {
					target = accumulated[len(accumulated)-1]
				} else {
					target = &ToolCall{
						Index: 0,
						Type:  "function",
					}
					accumulated = append(accumulated, target)
				}

				if tc.Function.Name != "" {
					if target.Function.Name == "" || target.Function.Name == tc.Function.Name {
						target.Function.Name = tc.Function.Name
					} else if !strings.Contains(target.Function.Name, tc.Function.Name) {
						// If a distinct new function name arrives without a new ID, start a new tool call
						target = &ToolCall{
							Index: len(accumulated),
							Type:  "function",
							Function: FunctionCall{
								Name: tc.Function.Name,
							},
						}
						accumulated = append(accumulated, target)
					}
				}
				if tc.Function.Arguments != "" {
					target.Function.Arguments += tc.Function.Arguments
				}
			}

			if choice.FinishReason != "" {
				finishReason = choice.FinishReason
			}
		}
		if err := scanner.Err(); err != nil {
			out <- StreamEvent{Err: fmt.Errorf("stream read error: %w", err)}
			return
		}

		var finalCalls []ToolCall
		for _, tc := range accumulated {
			name := sanitizeToolName(tc.Function.Name)
			args := sanitizeToolArguments(tc.Function.Arguments)
			id := tc.ID
			if id == "" {
				id = fmt.Sprintf("call_%d", tc.Index)
			}
			finalCalls = append(finalCalls, ToolCall{
				Index: tc.Index,
				ID:    id,
				Type:  "function",
				Function: FunctionCall{
					Name:      name,
					Arguments: args,
				},
			})
		}

		out <- StreamEvent{Done: true, ToolCalls: finalCalls, FinishReason: finishReason}
	}()

	return out
}

// isTransientUpstreamError identifies recoverable network/gateway errors suitable for transparent retry.
func isTransientUpstreamError(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	for _, marker := range []string{
		"502", "503", "504", "429", "upstream_error", "capacity", "overloaded", "rate limit",
		"deadline exceeded", "context canceled",
		"EOF",
		"connection reset",
	} {
		if strings.Contains(msg, marker) {
			return true
		}
	}
	return false
}

// streamChatWithRetry wraps streamChat with exponential backoff retries for transient initial connection failures.
func streamChatWithRetry(ctx context.Context, cfg *Config, messages []Message, tools []ToolSpec) <-chan StreamEvent {
	out := make(chan StreamEvent, 8)

	go func() {
		defer close(out)

		const maxAttempts = 3
		backoff := time.Second

		for attempt := 1; attempt <= maxAttempts; attempt++ {
			ch := streamChat(ctx, cfg, messages, tools)
			first, ok := <-ch
			if !ok {
				return
			}

			if first.Err != nil && isTransientUpstreamError(first.Err) && attempt < maxAttempts {
				select {
				case <-ctx.Done():
					out <- StreamEvent{Err: ctx.Err()}
					return
				case <-time.After(backoff):
				}
				backoff *= 2
				continue
			}

			out <- first
			for ev := range ch {
				out <- ev
			}
			return
		}
	}()

	return out
}

// pruneMessagesForContext trims long conversation history to stay comfortably within the model's context budget:
// 1. Always preserves the system prompt (index 0) and the initial user goal if available.
// 2. Compacts large historical tool outputs (> 2.5KB) from older turns into lightweight summaries.
// 3. Slices the conversation window to the most recent atomic turns.
// 4. Ensures tool calls and tool responses remain strictly paired.
func pruneMessagesForContext(msgs []Message) []Message {
	if len(msgs) <= 18 {
		return msgs
	}

	var systemMsg *Message
	var firstUserMsg *Message
	startIdx := 0

	if len(msgs) > 0 && msgs[0].Role == "system" {
		systemMsg = &msgs[0]
		startIdx = 1
	}

	if startIdx < len(msgs) && msgs[startIdx].Role == "user" {
		firstUserMsg = &msgs[startIdx]
	}

	// Keep the most recent 18 messages
	tailCount := 18
	if len(msgs)-startIdx < tailCount {
		tailCount = len(msgs) - startIdx
	}
	tailSlice := msgs[len(msgs)-tailCount:]

	// Find first clean user boundary in tailSlice
	cutIdx := 0
	for i, m := range tailSlice {
		if m.Role == "user" {
			cutIdx = i
			break
		}
	}
	recent := tailSlice[cutIdx:]

	// Compact older tool outputs in recent slice
	var compacted []Message
	for i, m := range recent {
		mCopy := m
		if m.Role == "tool" {
			if str, ok := m.Content.(string); ok && len(str) > 2500 && i < len(recent)-4 {
				mCopy.Content = str[:1200] + "\n... [truncated older output]"
			}
		}
		compacted = append(compacted, mCopy)
	}

	// Reassemble: system + (firstUser goal note if not already in recent) + compacted
	var out []Message
	if systemMsg != nil {
		out = append(out, *systemMsg)
	}
	if firstUserMsg != nil && len(compacted) > 0 {
		if str1, ok1 := firstUserMsg.Content.(string); ok1 {
			if str2, ok2 := compacted[0].Content.(string); !ok2 || str1 != str2 {
				out = append(out, Message{
					Role:    "user",
					Content: fmt.Sprintf("[Original user goal: %s]", str1),
				})
			}
		}
	}
	out = append(out, compacted...)

	return out
}

// cleanModelName strips provider namespace prefixes and resolves model aliases matching upstream OpenCode.
func cleanModelName(model string) string {
	model = strings.TrimSpace(model)
	if strings.HasPrefix(model, "openmind/") {
		model = strings.TrimPrefix(model, "openmind/")
	} else if strings.HasPrefix(model, "opencode/") {
		model = strings.TrimPrefix(model, "opencode/")
	} else if strings.HasPrefix(model, "custom/") {
		model = strings.TrimPrefix(model, "custom/")
	}
	switch model {
	case "ox-alpha", "ox-alpha-free", "x-preview-f-free":
		return "zen-x-preview-f-free"
	case "deepseek-flash", "deepseek-v4-flash":
		return "zen-go-deepseek-v4-flash"
	case "hy3", "hy3-free":
		return "zen-hy3-free"
	default:
		return model
	}
}
